using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace Geeklab.AudiencelabSDK.Editor
{
    /// <summary>
    /// Manages Android Gradle dependencies based on SDK settings.
    /// Automatically generates or removes the dependencies file before build.
    /// </summary>
    public class AndroidDependencyManager : IPreprocessBuildWithReport, IPostprocessBuildWithReport
    {
        private const string GradleFileName = "AudienceLabIdentity.gradle";
        private const string GeneratedGradlePath = "Assets/Plugins/Android/" + GradleFileName;
        private const string GeneratedGradleMetaPath = GeneratedGradlePath + ".meta";
        
        // Called before build - lower number = earlier execution
        public int callbackOrder => 0;

        public void OnPreprocessBuild(BuildReport report)
        {
            if (report.summary.platform != BuildTarget.Android)
            {
                return;
            }

            var settings = Resources.Load<AudienceLabSettings>("AudienceLabSettings");
            bool needsPlayServices = ShouldIncludePlayServicesDependencies(settings);

            EnsurePluginsAndroidFolderExists();

            if (needsPlayServices)
            {
                GenerateGradleFile();
                Debug.Log($"[AudienceLab] Generated {GradleFileName} with Play Services dependencies (Auto GAID mode)");
            }
            else
            {
                RemoveGradleFileIfExists();
                Debug.Log($"[AudienceLab] Play Services dependencies not required (GAID disabled or manual mode)");
            }

            AssetDatabase.Refresh();
        }

        public void OnPostprocessBuild(BuildReport report)
        {
            // Optional: Clean up the generated gradle file after build
            // Uncomment if you want to remove it after each build
            // RemoveGradleFileIfExists();
            // AssetDatabase.Refresh();
        }

        /// <summary>
        /// Determines if Play Services dependencies should be included based on settings.
        /// </summary>
        private static bool ShouldIncludePlayServicesDependencies(AudienceLabSettings settings)
        {
            if (settings == null)
            {
                // Default to including dependencies if settings not found
                return true;
            }

            // Include Play Services if Auto GAID is enabled
            // OR if App Set ID auto-collection is enabled (requires Play Services)
            return settings.enableGaidAutoCollection || settings.enableAppSetIdAutoCollection;
        }

        private static void EnsurePluginsAndroidFolderExists()
        {
            var path = Path.Combine(Application.dataPath, "Plugins", "Android");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
        }

        private static void GenerateGradleFile()
        {
            var content = @"// Generated by AudienceLab SDK - do not edit manually
// This file is regenerated based on SDK settings before each Android build
dependencies {
    implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'
    implementation 'com.google.android.gms:play-services-appset:16.0.2'
}
";
            var fullPath = Path.Combine(Application.dataPath, "Plugins", "Android", GradleFileName);
            File.WriteAllText(fullPath, content);
        }

        private static void RemoveGradleFileIfExists()
        {
            var fullPath = Path.Combine(Application.dataPath, "Plugins", "Android", GradleFileName);
            var fullMetaPath = fullPath + ".meta";

            if (File.Exists(fullPath))
            {
                File.Delete(fullPath);
            }

            if (File.Exists(fullMetaPath))
            {
                File.Delete(fullMetaPath);
            }
        }

        /// <summary>
        /// Menu item to manually regenerate the gradle file based on current settings.
        /// </summary>
        [MenuItem("Audiencelab SDK/Android/Regenerate Android Dependencies", false, 100)]
        public static void RegenerateAndroidDependencies()
        {
            var settings = Resources.Load<AudienceLabSettings>("AudienceLabSettings");
            bool needsPlayServices = ShouldIncludePlayServicesDependencies(settings);

            EnsurePluginsAndroidFolderExists();

            if (needsPlayServices)
            {
                GenerateGradleFile();
                Debug.Log($"[AudienceLab] Generated {GradleFileName} with Play Services dependencies");
            }
            else
            {
                RemoveGradleFileIfExists();
                Debug.Log($"[AudienceLab] Removed {GradleFileName} (Play Services dependencies not required)");
            }

            AssetDatabase.Refresh();
        }

        /// <summary>
        /// Menu item to check current dependency status.
        /// </summary>
        [MenuItem("Audiencelab SDK/Android/Check Android Dependencies", false, 101)]
        public static void CheckAndroidDependencies()
        {
            var settings = Resources.Load<AudienceLabSettings>("AudienceLabSettings");
            var gradleExists = File.Exists(Path.Combine(Application.dataPath, "Plugins", "Android", GradleFileName));

            string gaidMode = "Unknown";
            bool needsDeps = true;

            if (settings != null)
            {
                if (settings.enableGaidAutoCollection)
                    gaidMode = "Auto GAID";
                else if (settings.enableGaidManualMode)
                    gaidMode = "Manual GAID";
                else
                    gaidMode = "No GAID";

                needsDeps = settings.enableGaidAutoCollection || settings.enableAppSetIdAutoCollection;
            }

            Debug.Log($"[AudienceLab] Android Dependency Status:\n" +
                      $"  - GAID Mode: {gaidMode}\n" +
                      $"  - App Set ID Auto: {(settings?.enableAppSetIdAutoCollection ?? true)}\n" +
                      $"  - Play Services Required: {needsDeps}\n" +
                      $"  - Gradle File Present: {gradleExists}");
        }
    }
}
